### ISSUE TITLE
Test/document compatible versions of fluentd

### ISSUE THREAD

**Issue by emfree** [honeycombio/fluent-plugin-honeycomb#13]
We should document and test which versions of fluentd this plugin is compatible with. Currently works with 0.12 and 0.14 at least, but we should test 1.x as well.

**Comment by cosmo0920** [comment]
Fluentd v1 is as a just bumping version from v0.14. This version's functionality is same as v0.14.

**Comment by martin308** [comment]
Added testing in #18
