### ISSUE TITLE
Dynamic Datasets

### ISSUE THREAD

**Issue by bacoboy** [honeycombio/fluent-plugin-honeycomb#5]
Since the write key can be used for any data set within a team, it would be nice to specify a json key to be used as the dataset name.  Let's call this parameter `dataset_from_key` which cannot be specified at the same time as `dataset`.  If specified the value of the `dataset_from_key` entry would be used for the dataset.  This key would _NOT_ be part of the payload sent to honeycomb.

The advantage of this would be not having to setup multiple matches/outputs for each dataset.  Since datasets can be created on the fly, this seem to jive with the honeycomb mission of write key's being team specific.  Translated to fluentd terms, a team aligns with a output, not a dataset.

For example:
```
<match ship_to_honeycomb>
  @type honeycomb
  writekey "WRITE_KEY"
  dataset_from_key "honeycomb"
</match>
```

The following payload:
```json
{
  "honeycomb": "http_stats",
  "status": 200,
  "path": "/docs/",
  "latency_ms": 13.1,
  "cached": false
}
```

Would be equivalent to this curl:
```
curl https://api.honeycomb.io/1/events/http_stats -X POST \
  -H "X-Honeycomb-Team: WRITE_KEY" \
  -d '{"status":200,"path":"/docs/","latency_ms":13.1,"cached":false}'
```

**Comment by bacoboy** [comment]
One more thought since the `sample_rate` is also a property of the dataset and not the team, perhaps we also need a `sample_rate_from_tag` to specify a tag containing an override of the default `sample_rate`.  Of course that puts the onus of specifying the sampling rate on the data producer and not the shipper which I don't love.

I'm open to ideas on this or we just leave it for now and IF alternate sampling is needed by data set we create another match block.

**Comment by emfree** [comment]
Thanks for filing this issue! PR #6 adds support for routing events to different datasets based on a `dataset_from_key` option.

You raise a good point about the sample rate as well. In truth, it may be best to properly implement dynamic sampling (e.g., "keep all errors, but sample common events"), perhaps as a separate plugin. Going to think about that one a little more.

**Comment by bacoboy** [comment]
Yea we were thinking the same thing.  We'd sample the high volume happy path, but get 1:1 on error-ish events.  That's why I was thinking of some kind of extra tag to say something was "sample-ale" or not.  Then I could manage the sampling rate outside the application in fluentd.

**Comment by emfree** [comment]
If you install version 0.5.0 of this plugin you can now set a `dataset_from_key` option; please let us know if you encounter any issues!
